import { boolean, index, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { energyDataSources, energyParties, energySites } from './core';

export const energyEnergyTypes = pgTable('energy_energy_types', {
  code: text('code').primaryKey(),
  name: text('name').notNull(),
  category: text('category').notNull(),
  canonicalUnit: text('canonical_unit'),
  description: text('description'),
  status: text('status').notNull().default('ACTIVE'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index('energy_energy_types_category_status_idx').on(t.category, t.status)]);

export const energyEmissionSources = pgTable('energy_emission_sources', {
  id: uuid('id').defaultRandom().primaryKey(),
  partyId: uuid('party_id').references(() => energyParties.id, { onDelete: 'set null' }),
  siteId: uuid('site_id').references(() => energySites.id, { onDelete: 'set null' }),
  code: text('code').notNull(),
  name: text('name').notNull(),
  sourceType: text('source_type').notNull(),
  energyTypeCode: text('energy_type_code').references(() => energyEnergyTypes.code, { onDelete: 'restrict' }),
  fuelTypeCode: text('fuel_type_code'),
  processType: text('process_type'),
  equipmentRef: text('equipment_ref'),
  meterRef: text('meter_ref'),
  sourceCategory: text('source_category'),
  scope: text('scope').notNull(),
  sector: text('sector'),
  status: text('status').notNull().default('ACTIVE'),
  classification: text('classification').notNull().default('INTERNAL'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('energy_emission_sources_code_uq').on(t.code), index('energy_emission_sources_type_idx').on(t.sourceType, t.energyTypeCode, t.status), index('energy_emission_sources_site_idx').on(t.siteId, t.status)]);

export const energyVbdhSyncRuns = pgTable('energy_vbdh_sync_runs', {
  id: uuid('id').defaultRandom().primaryKey(),
  sourceId: uuid('source_id').references(() => energyDataSources.id, { onDelete: 'set null' }),
  mode: text('mode').notNull().default('RAW_IMPORT'),
  endpointRef: text('endpoint_ref'),
  startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  status: text('status').notNull().default('RECEIVED'),
  recordsReceived: integer('records_received').notNull().default(0),
  recordsMapped: integer('records_mapped').notNull().default(0),
  recordsNeedsReview: integer('records_needs_review').notNull().default(0),
  recordsRejected: integer('records_rejected').notNull().default(0),
  errorMessage: text('error_message'),
  createdBy: text('created_by'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
}, (t) => [index('energy_vbdh_sync_runs_status_time_idx').on(t.status, t.startedAt)]);

export const energyVbdhRecords = pgTable('energy_vbdh_records', {
  id: uuid('id').defaultRandom().primaryKey(),
  syncRunId: uuid('sync_run_id').notNull().references(() => energyVbdhSyncRuns.id, { onDelete: 'cascade' }),
  sourceId: uuid('source_id').references(() => energyDataSources.id, { onDelete: 'set null' }),
  sourceRecordId: text('source_record_id').notNull(),
  documentNo: text('document_no'),
  sourceDocumentRef: text('source_document_ref'),
  sourceUrl: text('source_url'),
  senderUnit: text('sender_unit'),
  issuedAt: timestamp('issued_at', { withTimezone: true }),
  receivedAt: timestamp('received_at', { withTimezone: true }),
  fetchedAt: timestamp('fetched_at', { withTimezone: true }).notNull().defaultNow(),
  rawPayload: jsonb('raw_payload').$type<Record<string, unknown>>().notNull().default({}),
  rawText: text('raw_text'),
  checksum: text('checksum'),
  parserVersion: text('parser_version').notNull(),
  mappingVersion: text('mapping_version').notNull(),
  validationStatus: text('validation_status').notNull().default('NEEDS_REVIEW'),
  mappedSourceId: uuid('mapped_source_id'),
  mappedActivityId: uuid('mapped_activity_id'),
  mappedMeasurementId: uuid('mapped_measurement_id'),
  errorMessage: text('error_message'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('energy_vbdh_records_source_key_uq').on(t.sourceId, t.sourceRecordId), index('energy_vbdh_records_run_status_idx').on(t.syncRunId, t.validationStatus), index('energy_vbdh_records_document_idx').on(t.documentNo)]);

export const energyVbdhFieldMappings = pgTable('energy_vbdh_field_mappings', {
  id: uuid('id').defaultRandom().primaryKey(),
  mappingCode: text('mapping_code').notNull(),
  versionNo: integer('version_no').notNull().default(1),
  sourceField: text('source_field').notNull(),
  canonicalField: text('canonical_field').notNull(),
  required: boolean('required').notNull().default(false),
  status: text('status').notNull().default('ACTIVE'),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('energy_vbdh_field_mappings_version_uq').on(t.mappingCode, t.versionNo, t.sourceField), index('energy_vbdh_field_mappings_status_idx').on(t.status, t.mappingCode)]);

export const energyEmissionFactors = pgTable('energy_emission_factors', {
  id: uuid('id').defaultRandom().primaryKey(),
  code: text('code').notNull(),
  gas: text('gas').notNull(),
  activityType: text('activity_type').notNull(),
  factorValue: numeric('factor_value', { precision: 20, scale: 8 }).notNull(),
  factorUnit: text('factor_unit').notNull(),
  sourceRef: text('source_ref').notNull(),
  sourceVersion: text('source_version').notNull(),
  validFrom: timestamp('valid_from', { withTimezone: true }).notNull(),
  validTo: timestamp('valid_to', { withTimezone: true }),
}, (t) => [uniqueIndex('energy_emission_factors_code_version_uq').on(t.code, t.sourceVersion)]);

export const energyEmissionActivities = pgTable('energy_emission_activities', {
  id: uuid('id').defaultRandom().primaryKey(),
  sourceId: uuid('source_id').notNull().references(() => energyEmissionSources.id, { onDelete: 'cascade' }),
  factorId: uuid('factor_id').notNull().references(() => energyEmissionFactors.id, { onDelete: 'restrict' }),
  vbdhRecordId: uuid('vbdh_record_id'),
  period: text('period').notNull(),
  quantity: numeric('quantity', { precision: 20, scale: 5 }).notNull(),
  activityUnit: text('activity_unit').notNull(),
  co2eKg: numeric('co2e_kg', { precision: 20, scale: 5 }).notNull(),
  noxKg: numeric('nox_kg', { precision: 20, scale: 5 }),
  soxKg: numeric('sox_kg', { precision: 20, scale: 5 }),
  sourceSystem: text('source_system').notNull().default('MANUAL'),
  sourceDocumentRef: text('source_document_ref'),
  status: text('status').notNull().default('DRAFT'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
}, (t) => [index('energy_emission_activities_source_period_idx').on(t.sourceId, t.period), index('energy_emission_activities_vbdh_idx').on(t.vbdhRecordId)]);

export const energyEmissionMeasurements = pgTable('energy_emission_measurements', {
  id: uuid('id').defaultRandom().primaryKey(),
  sourceId: uuid('source_id').notNull().references(() => energyEmissionSources.id, { onDelete: 'cascade' }),
  vbdhRecordId: uuid('vbdh_record_id'),
  metricCode: text('metric_code').notNull(),
  periodFrom: timestamp('period_from', { withTimezone: true }),
  periodTo: timestamp('period_to', { withTimezone: true }),
  measuredAt: timestamp('measured_at', { withTimezone: true }),
  value: numeric('value', { precision: 20, scale: 8 }).notNull(),
  unit: text('unit').notNull(),
  measurementMethod: text('measurement_method'),
  instrumentRef: text('instrument_ref'),
  sourceSystem: text('source_system').notNull().default('MANUAL'),
  sourceRecordId: text('source_record_id'),
  sourceDocumentRef: text('source_document_ref'),
  quality: text('quality').notNull().default('REPORTED'),
  verificationStatus: text('verification_status').notNull().default('DRAFT'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index('energy_emission_measurements_source_time_idx').on(t.sourceId, t.measuredAt), index('energy_emission_measurements_metric_status_idx').on(t.metricCode, t.verificationStatus), uniqueIndex('energy_emission_measurements_source_key_uq').on(t.sourceId, t.metricCode, t.measuredAt, t.sourceRecordId)]);

export const energyUnitDefinitions = pgTable('energy_unit_definitions', {
  code: text('code').primaryKey(),
  name: text('name').notNull(),
  dimension: text('dimension').notNull(),
  canonicalUnit: text('canonical_unit').notNull(),
  multiplierToCanonical: numeric('multiplier_to_canonical', { precision: 30, scale: 15 }).notNull(),
  status: text('status').notNull().default('ACTIVE'),
  sourceRef: text('source_ref'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index('energy_unit_definitions_dimension_idx').on(t.dimension, t.status)]);

export const energyUnitConversions = pgTable('energy_unit_conversions', {
  id: uuid('id').defaultRandom().primaryKey(),
  fromUnit: text('from_unit').notNull().references(() => energyUnitDefinitions.code, { onDelete: 'restrict' }),
  toUnit: text('to_unit').notNull().references(() => energyUnitDefinitions.code, { onDelete: 'restrict' }),
  factor: numeric('factor', { precision: 30, scale: 15 }).notNull(),
  sourceRef: text('source_ref'),
  versionNo: integer('version_no').notNull().default(1),
  validFrom: timestamp('valid_from', { withTimezone: true }),
  validTo: timestamp('valid_to', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('energy_unit_conversions_path_uq').on(t.fromUnit, t.toUnit, t.versionNo), index('energy_unit_conversions_validity_idx').on(t.fromUnit, t.toUnit, t.validFrom, t.validTo)]);

export const energyEmissionCalculationRuns = pgTable('energy_emission_calculation_runs', {
  id: uuid('id').defaultRandom().primaryKey(),
  activityId: uuid('activity_id').notNull().references(() => energyEmissionActivities.id, { onDelete: 'cascade' }),
  methodCode: text('method_code').notNull(),
  methodVersion: text('method_version').notNull(),
  factorId: uuid('factor_id').references(() => energyEmissionFactors.id, { onDelete: 'set null' }),
  inputHash: text('input_hash').notNull(),
  inputSnapshot: jsonb('input_snapshot').$type<Record<string, unknown>>().notNull().default({}),
  outputSnapshot: jsonb('output_snapshot').$type<Record<string, unknown>>().notNull().default({}),
  calculatedAt: timestamp('calculated_at', { withTimezone: true }).notNull().defaultNow(),
  calculatedBy: text('calculated_by'),
  quality: text('quality').notNull().default('NEEDS_REVIEW'),
  reviewStatus: text('review_status').notNull().default('PENDING_REVIEW'),
  reviewedBy: text('reviewed_by'),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  reviewNote: text('review_note'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index('energy_emission_calculation_runs_activity_idx').on(t.activityId, t.calculatedAt), index('energy_emission_calculation_runs_review_idx').on(t.reviewStatus, t.calculatedAt), uniqueIndex('energy_emission_calculation_runs_input_uq').on(t.activityId, t.inputHash)]);

export const energyReductionPlans = pgTable('energy_reduction_plans', {
  id: uuid('id').defaultRandom().primaryKey(),
  partyId: uuid('party_id').notNull().references(() => energyParties.id, { onDelete: 'cascade' }),
  code: text('code').notNull(),
  name: text('name').notNull(),
  baselineYear: numeric('baseline_year', { precision: 4, scale: 0 }).notNull(),
  targetYear: numeric('target_year', { precision: 4, scale: 0 }).notNull(),
  baselineCo2eKg: numeric('baseline_co2e_kg', { precision: 20, scale: 5 }).notNull(),
  targetReductionPct: numeric('target_reduction_pct', { precision: 7, scale: 3 }).notNull(),
  status: text('status').notNull().default('DRAFT'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
}, (t) => [uniqueIndex('energy_reduction_plans_code_uq').on(t.code)]);

export const energyReductionProgress = pgTable('energy_reduction_progress', {
  id: uuid('id').defaultRandom().primaryKey(),
  planId: uuid('plan_id').notNull().references(() => energyReductionPlans.id, { onDelete: 'cascade' }),
  period: text('period').notNull(),
  actualCo2eKg: numeric('actual_co2e_kg', { precision: 20, scale: 5 }).notNull(),
  reductionPct: numeric('reduction_pct', { precision: 9, scale: 4 }),
  status: text('status').notNull().default('RECORDED'),
  evidenceRef: text('evidence_ref'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('energy_reduction_progress_plan_period_uq').on(t.planId, t.period), index('energy_reduction_progress_period_idx').on(t.period)]);

export const energyReductionPlanTargets = pgTable('energy_reduction_plan_targets', {
  id: uuid('id').defaultRandom().primaryKey(),
  planId: uuid('plan_id').notNull().references(() => energyReductionPlans.id, { onDelete: 'cascade' }),
  year: integer('year').notNull(),
  targetCo2eKg: numeric('target_co2e_kg', { precision: 20, scale: 5 }).notNull(),
  targetReductionPct: numeric('target_reduction_pct', { precision: 9, scale: 4 }).notNull(),
  status: text('status').notNull().default('PLANNED'),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('energy_reduction_plan_targets_plan_year_uq').on(t.planId, t.year), index('energy_reduction_plan_targets_status_idx').on(t.status, t.year)]);

export const energyReductionActions = pgTable('energy_reduction_actions', {
  id: uuid('id').defaultRandom().primaryKey(),
  planId: uuid('plan_id').notNull().references(() => energyReductionPlans.id, { onDelete: 'cascade' }),
  code: text('code').notNull(),
  name: text('name').notNull(),
  actionType: text('action_type').notNull(),
  sourceId: uuid('source_id').references(() => energyEmissionSources.id, { onDelete: 'set null' }),
  siteId: uuid('site_id').references(() => energySites.id, { onDelete: 'set null' }),
  owner: text('owner'),
  startAt: timestamp('start_at', { withTimezone: true }),
  targetAt: timestamp('target_at', { withTimezone: true }),
  budget: numeric('budget', { precision: 20, scale: 3 }),
  expectedReductionTco2eYear: numeric('expected_reduction_tco2e_year', { precision: 20, scale: 5 }),
  actualReductionTco2eYear: numeric('actual_reduction_tco2e_year', { precision: 20, scale: 5 }),
  status: text('status').notNull().default('PLANNED'),
  method: text('method'),
  verificationRequired: boolean('verification_required').notNull().default(true),
  evidenceRef: text('evidence_ref'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('energy_reduction_actions_plan_code_uq').on(t.planId, t.code), index('energy_reduction_actions_status_idx').on(t.status, t.targetAt)]);

export const energyReductionActionProgress = pgTable('energy_reduction_action_progress', {
  id: uuid('id').defaultRandom().primaryKey(),
  actionId: uuid('action_id').notNull().references(() => energyReductionActions.id, { onDelete: 'cascade' }),
  period: text('period').notNull(),
  actualCo2eKg: numeric('actual_co2e_kg', { precision: 20, scale: 5 }).notNull(),
  reductionPct: numeric('reduction_pct', { precision: 9, scale: 4 }),
  evidenceRef: text('evidence_ref'),
  verifiedBy: text('verified_by'),
  verifiedAt: timestamp('verified_at', { withTimezone: true }),
  status: text('status').notNull().default('RECORDED'),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('energy_reduction_action_progress_period_uq').on(t.actionId, t.period), index('energy_reduction_action_progress_period_idx').on(t.period, t.status)]);

export const energyCarbonProjects = pgTable('energy_carbon_projects', {
  id: uuid('id').defaultRandom().primaryKey(),
  code: text('code').notNull(),
  name: text('name').notNull(),
  partyId: uuid('party_id').references(() => energyParties.id, { onDelete: 'set null' }),
  siteId: uuid('site_id').references(() => energySites.id, { onDelete: 'set null' }),
  projectType: text('project_type').notNull(),
  methodology: text('methodology').notNull(),
  registry: text('registry'),
  validationRef: text('validation_ref'),
  verificationRef: text('verification_ref'),
  startDate: timestamp('start_date', { withTimezone: true }),
  creditingPeriodFrom: timestamp('crediting_period_from', { withTimezone: true }),
  creditingPeriodTo: timestamp('crediting_period_to', { withTimezone: true }),
  status: text('status').notNull().default('DRAFT'),
  notes: text('notes'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('energy_carbon_projects_code_uq').on(t.code), index('energy_carbon_projects_status_idx').on(t.status, t.partyId)]);

export const energyCarbonCreditBatches = pgTable('energy_carbon_credit_batches', {
  id: uuid('id').defaultRandom().primaryKey(),
  projectId: uuid('project_id').references(() => energyCarbonProjects.id, { onDelete: 'set null' }),
  registry: text('registry').notNull(),
  batchRef: text('batch_ref').notNull(),
  serialFrom: text('serial_from'),
  serialTo: text('serial_to'),
  vintageYear: integer('vintage_year').notNull(),
  issuedAt: timestamp('issued_at', { withTimezone: true }).notNull(),
  quantityTco2e: numeric('quantity_tco2e', { precision: 20, scale: 5 }).notNull(),
  status: text('status').notNull().default('ISSUED'),
  evidenceRef: text('evidence_ref'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('energy_carbon_credit_batches_registry_ref_uq').on(t.registry, t.batchRef), uniqueIndex('energy_carbon_credit_batches_serial_uq').on(t.registry, t.serialFrom, t.serialTo), index('energy_carbon_credit_batches_vintage_status_idx').on(t.vintageYear, t.status)]);

export const energyCarbonCreditTransactions = pgTable('energy_carbon_credit_transactions', {
  id: uuid('id').defaultRandom().primaryKey(),
  creditBatchId: uuid('credit_batch_id').notNull().references(() => energyCarbonCreditBatches.id, { onDelete: 'cascade' }),
  transactionType: text('transaction_type').notNull(),
  quantityTco2e: numeric('quantity_tco2e', { precision: 20, scale: 5 }).notNull(),
  balanceDeltaTco2e: numeric('balance_delta_tco2e', { precision: 20, scale: 5 }).notNull(),
  fromPartyId: uuid('from_party_id').references(() => energyParties.id, { onDelete: 'set null' }),
  toPartyId: uuid('to_party_id').references(() => energyParties.id, { onDelete: 'set null' }),
  occurredAt: timestamp('occurred_at', { withTimezone: true }).notNull().defaultNow(),
  reference: text('reference'),
  certificateRef: text('certificate_ref'),
  reason: text('reason'),
  createdBy: text('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index('energy_carbon_credit_transactions_batch_time_idx').on(t.creditBatchId, t.occurredAt), index('energy_carbon_credit_transactions_type_idx').on(t.transactionType, t.occurredAt)]);

export const energyCarbonCredits = pgTable('energy_carbon_credits', {
  id: uuid('id').defaultRandom().primaryKey(),
  partyId: uuid('party_id').references(() => energyParties.id, { onDelete: 'set null' }),
  registry: text('registry').notNull(),
  reference: text('reference').notNull(),
  vintageYear: numeric('vintage_year', { precision: 4, scale: 0 }).notNull(),
  quantityTco2e: numeric('quantity_tco2e', { precision: 18, scale: 4 }).notNull(),
  status: text('status').notNull().default('AVAILABLE'),
}, (t) => [uniqueIndex('energy_carbon_credits_registry_ref_uq').on(t.registry, t.reference)]);

export const energyReportingObligations = pgTable('energy_reporting_obligations', {
  id: uuid('id').defaultRandom().primaryKey(),
  partyId: uuid('party_id').notNull().references(() => energyParties.id, { onDelete: 'cascade' }),
  reportingProgram: text('reporting_program'),
  legalBasis: text('legal_basis'),
  reportTemplate: text('report_template'),
  reportType: text('report_type').notNull(),
  period: text('period').notNull(),
  periodFrom: timestamp('period_from', { withTimezone: true }),
  periodTo: timestamp('period_to', { withTimezone: true }),
  versionNo: integer('version_no').notNull().default(1),
  requiredFields: jsonb('required_fields').$type<string[]>().notNull().default([]),
  dueAt: timestamp('due_at', { withTimezone: true }).notNull(),
  status: text('status').notNull().default('PENDING'),
  sourceSystem: text('source_system').notNull().default('VBDH'),
  sourceDocumentRef: text('source_document_ref'),
}, (t) => [uniqueIndex('energy_reporting_obligations_party_period_uq').on(t.partyId, t.reportType, t.period), index('energy_reporting_obligations_due_idx').on(t.status, t.dueAt)]);

export const energyCarbonReportSubmissions = pgTable('energy_carbon_report_submissions', {
  id: uuid('id').defaultRandom().primaryKey(),
  obligationId: uuid('obligation_id').notNull().references(() => energyReportingObligations.id, { onDelete: 'cascade' }),
  submittedAt: timestamp('submitted_at', { withTimezone: true }).notNull().defaultNow(),
  status: text('status').notNull().default('SUBMITTED'),
  totalCo2eKg: numeric('total_co2e_kg', { precision: 20, scale: 5 }),
  documentRef: text('document_ref'),
  sourceSystem: text('source_system').notNull().default('VBDH'),
  sourceRecordId: text('source_record_id'),
  reviewedBy: text('reviewed_by'),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  reviewDecision: text('review_decision'),
  reviewNote: text('review_note'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
}, (t) => [index('energy_carbon_submissions_obligation_idx').on(t.obligationId, t.submittedAt), index('energy_carbon_submissions_status_idx').on(t.status, t.submittedAt)]);
