import { boolean, index, integer, jsonb, numeric, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { energyAssets, energyDataSources, energyMeasurementPoints, energyParties, energySites, geometry } from './core';
import { energyGridCapacityAssessments } from './grid';

export const energyCustomerAccounts = pgTable('energy_customer_accounts', {
  id: uuid('id').defaultRandom().primaryKey(),
  partyId: uuid('party_id').notNull().references(() => energyParties.id, { onDelete: 'cascade' }),
  provider: text('provider').notNull().default('EVN'),
  customerCode: text('customer_code').notNull(),
  serviceAddress: text('service_address'),
  siteId: uuid('site_id').references(() => energySites.id, { onDelete: 'set null' }),
  customerType: text('customer_type'),
  status: text('status').notNull().default('ACTIVE'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
}, (t) => [uniqueIndex('energy_customer_accounts_provider_code_uq').on(t.provider, t.customerCode)]);

export const energyCustomerConsumptionMonthly = pgTable('energy_customer_consumption_monthly', {
  id: uuid('id').defaultRandom().primaryKey(),
  accountId: uuid('account_id').notNull().references(() => energyCustomerAccounts.id, { onDelete: 'cascade' }),
  period: text('period').notNull(),
  energyKwh: numeric('energy_kwh', { precision: 18, scale: 3 }).notNull(),
  peakDemandKw: numeric('peak_demand_kw', { precision: 14, scale: 3 }),
  daytimeSharePct: numeric('daytime_share_pct', { precision: 7, scale: 3 }),
  source: text('source').notNull().default('EVN'),
}, (t) => [uniqueIndex('energy_customer_consumption_month_uq').on(t.accountId, t.period)]);

export const energyBuildings = pgTable('energy_buildings', {
  assetId: uuid('asset_id').primaryKey().references(() => energyAssets.id, { onDelete: 'cascade' }),
  siteId: uuid('site_id').references(() => energySites.id, { onDelete: 'set null' }),
  buildingType: text('building_type').notNull(),
  heightM: numeric('height_m', { precision: 10, scale: 3 }),
  floorCount: integer('floor_count'),
  footprint: geometry('footprint'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
}, (t) => [index('energy_buildings_footprint_gist').using('gist', t.footprint)]);

export const energySolarResourceZones = pgTable('energy_solar_resource_zones', {
  id: uuid('id').defaultRandom().primaryKey(),
  code: text('code').notNull(),
  name: text('name').notNull(),
  boundary: geometry('boundary'),
  annualGhiKwhM2: numeric('annual_ghi_kwh_m2', { precision: 14, scale: 3 }).notNull(),
  annualDniKwhM2: numeric('annual_dni_kwh_m2', { precision: 14, scale: 3 }),
  annualDhiKwhM2: numeric('annual_dhi_kwh_m2', { precision: 14, scale: 3 }),
  referenceTiltDeg: numeric('reference_tilt_deg', { precision: 8, scale: 3 }),
  referenceAzimuthDeg: numeric('reference_azimuth_deg', { precision: 8, scale: 3 }),
  source: text('source').notNull().default('MANUAL'),
  sourceVersion: text('source_version').notNull(),
  sourceRef: text('source_ref'),
  measuredFrom: timestamp('measured_from', { withTimezone: true }),
  measuredTo: timestamp('measured_to', { withTimezone: true }),
  quality: text('quality').notNull().default('ESTIMATED'),
  confidence: numeric('confidence', { precision: 7, scale: 3 }),
  status: text('status').notNull().default('ACTIVE'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex('energy_solar_resource_zones_code_uq').on(t.code),
  index('energy_solar_resource_zones_boundary_gist').using('gist', t.boundary),
  index('energy_solar_resource_zones_status_idx').on(t.status),
]);

export const energyRoofSurfaces = pgTable('energy_roof_surfaces', {
  id: uuid('id').defaultRandom().primaryKey(),
  buildingAssetId: uuid('building_asset_id').notNull().references(() => energyAssets.id, { onDelete: 'cascade' }),
  code: text('code').notNull(),
  geometry: geometry('geometry'),
  solarResourceZoneId: uuid('solar_resource_zone_id').references(() => energySolarResourceZones.id, { onDelete: 'set null' }),
  areaM2: numeric('area_m2', { precision: 14, scale: 3 }).notNull(),
  usableAreaM2: numeric('usable_area_m2', { precision: 14, scale: 3 }),
  tiltDeg: numeric('tilt_deg', { precision: 8, scale: 3 }),
  azimuthDeg: numeric('azimuth_deg', { precision: 8, scale: 3 }),
  material: text('material'),
  shadingFactor: numeric('shading_factor', { precision: 8, scale: 5 }),
  source: text('source').notNull().default('MANUAL_SURVEY'),
  sourceCapturedAt: timestamp('source_captured_at', { withTimezone: true }),
  sourceResolutionM: numeric('source_resolution_m', { precision: 10, scale: 3 }),
  confidence: numeric('confidence', { precision: 7, scale: 3 }),
  obstructionRatioPct: numeric('obstruction_ratio_pct', { precision: 7, scale: 3 }),
  structuralSuitabilityStatus: text('structural_suitability_status'),
  orientationQuality: text('orientation_quality'),
  sourceRef: text('source_ref'),
  status: text('status').notNull().default('ACTIVE'),
  lastVerifiedAt: timestamp('last_verified_at', { withTimezone: true }),
}, (t) => [
  uniqueIndex('energy_roof_surfaces_building_code_uq').on(t.buildingAssetId, t.code),
  index('energy_roof_surfaces_geometry_gist').using('gist', t.geometry),
  index('energy_roof_surfaces_resource_idx').on(t.solarResourceZoneId),
  index('energy_roof_surfaces_status_idx').on(t.status),
]);

export const energyRooftopSystems = pgTable('energy_rooftop_systems', {
  assetId: uuid('asset_id').primaryKey().references(() => energyAssets.id, { onDelete: 'cascade' }),
  customerAccountId: uuid('customer_account_id').references(() => energyCustomerAccounts.id, { onDelete: 'set null' }),
  buildingAssetId: uuid('building_asset_id').references(() => energyAssets.id, { onDelete: 'set null' }),
  installedCapacityKwp: numeric('installed_capacity_kwp', { precision: 14, scale: 3 }).notNull(),
  inverterCapacityKw: numeric('inverter_capacity_kw', { precision: 14, scale: 3 }),
  batteryCapacityKwh: numeric('battery_capacity_kwh', { precision: 14, scale: 3 }),
  gridConnectionAssetId: uuid('grid_connection_asset_id').references(() => energyAssets.id, { onDelete: 'set null' }),
  annualYieldKwh: numeric('annual_yield_kwh', { precision: 18, scale: 3 }),
  selfConsumptionPct: numeric('self_consumption_pct', { precision: 7, scale: 3 }),
  operationStatus: text('operation_status').notNull().default('ACTIVE'),
  ownershipModel: text('ownership_model'),
  installationType: text('installation_type').notNull().default('ROOFTOP'),
  installerPartyId: uuid('installer_party_id').references(() => energyParties.id, { onDelete: 'set null' }),
  evRegistrationNo: text('ev_registration_no'),
  evnAcceptanceAt: timestamp('evn_acceptance_at', { withTimezone: true }),
  meteringScheme: text('metering_scheme'),
  exportLimitKw: numeric('export_limit_kw', { precision: 14, scale: 3 }),
  source: text('source').notNull().default('MANUAL'),
  sourceId: uuid('source_id').references(() => energyDataSources.id, { onDelete: 'set null' }),
  sourceRef: text('source_ref'),
  lastVerifiedAt: timestamp('last_verified_at', { withTimezone: true }),
  confidence: numeric('confidence', { precision: 7, scale: 3 }),
  roofSurfaceId: uuid('roof_surface_id').references(() => energyRoofSurfaces.id, { onDelete: 'set null' }),
});

export const energyRooftopSystemComponents = pgTable('energy_rooftop_system_components', {
  id: uuid('id').defaultRandom().primaryKey(),
  systemAssetId: uuid('system_asset_id').notNull().references(() => energyRooftopSystems.assetId, { onDelete: 'cascade' }),
  componentType: text('component_type').notNull(),
  manufacturer: text('manufacturer'),
  model: text('model'),
  serialNumber: text('serial_number'),
  quantity: integer('quantity').notNull().default(1),
  ratedPower: numeric('rated_power', { precision: 14, scale: 3 }),
  unit: text('unit'),
  commissionedAt: timestamp('commissioned_at', { withTimezone: true }),
  warrantyUntil: timestamp('warranty_until', { withTimezone: true }),
  source: text('source').notNull().default('MANUAL'),
  sourceRef: text('source_ref'),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index('energy_rooftop_components_system_idx').on(t.systemAssetId), uniqueIndex('energy_rooftop_components_serial_uq').on(t.systemAssetId, t.serialNumber)]);

export const energyRooftopGenerationMonthly = pgTable('energy_rooftop_generation_monthly', {
  id: uuid('id').defaultRandom().primaryKey(),
  systemAssetId: uuid('system_asset_id').notNull().references(() => energyRooftopSystems.assetId, { onDelete: 'cascade' }),
  period: text('period').notNull(),
  energyGeneratedKwh: numeric('energy_generated_kwh', { precision: 18, scale: 3 }).notNull(),
  energySelfConsumedKwh: numeric('energy_self_consumed_kwh', { precision: 18, scale: 3 }),
  energyExportedKwh: numeric('energy_exported_kwh', { precision: 18, scale: 3 }),
  energyImportedKwh: numeric('energy_imported_kwh', { precision: 18, scale: 3 }),
  peakGenerationKw: numeric('peak_generation_kw', { precision: 14, scale: 3 }),
  source: text('source').notNull().default('MANUAL'),
  sourceId: uuid('source_id').references(() => energyDataSources.id, { onDelete: 'set null' }),
  sourceRef: text('source_ref'),
  quality: text('quality').notNull().default('GOOD'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('energy_rooftop_generation_system_period_uq').on(t.systemAssetId, t.period), index('energy_rooftop_generation_period_idx').on(t.period)]);

export const energyRooftopSystemDocuments = pgTable('energy_rooftop_system_documents', {
  id: uuid('id').defaultRandom().primaryKey(),
  systemAssetId: uuid('system_asset_id').notNull().references(() => energyRooftopSystems.assetId, { onDelete: 'cascade' }),
  documentType: text('document_type').notNull(),
  documentNo: text('document_no'),
  title: text('title').notNull(),
  issuedAt: timestamp('issued_at', { withTimezone: true }),
  fileRef: text('file_ref'),
  source: text('source').notNull().default('MANUAL'),
  sourceRef: text('source_ref'),
  notes: text('notes'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index('energy_rooftop_documents_system_idx').on(t.systemAssetId)]);

export const energyCustomerGridServiceLinks = pgTable('energy_customer_grid_service_links', {
  id: uuid('id').defaultRandom().primaryKey(),
  customerAccountId: uuid('customer_account_id').notNull().references(() => energyCustomerAccounts.id, { onDelete: 'cascade' }),
  servicePointCode: text('service_point_code').notNull(),
  measurementPointId: uuid('measurement_point_id').references(() => energyMeasurementPoints.id, { onDelete: 'set null' }),
  feederAssetId: uuid('feeder_asset_id').references(() => energyAssets.id, { onDelete: 'set null' }),
  bayAssetId: uuid('bay_asset_id').references(() => energyAssets.id, { onDelete: 'set null' }),
  transformerAssetId: uuid('transformer_asset_id').references(() => energyAssets.id, { onDelete: 'set null' }),
  substationAssetId: uuid('substation_asset_id').references(() => energyAssets.id, { onDelete: 'set null' }),
  validFrom: timestamp('valid_from', { withTimezone: true }),
  validTo: timestamp('valid_to', { withTimezone: true }),
  source: text('source').notNull().default('EVN'),
  sourceId: uuid('source_id').references(() => energyDataSources.id, { onDelete: 'set null' }),
  sourceRef: text('source_ref'),
  confidence: numeric('confidence', { precision: 7, scale: 3 }),
  isInferred: boolean('is_inferred').notNull().default(false),
  metadata: jsonb('metadata').$type<Record<string, unknown>>().notNull().default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [index('energy_customer_grid_links_account_valid_idx').on(t.customerAccountId, t.validFrom), index('energy_customer_grid_links_feeder_idx').on(t.feederAssetId)]);

export const energySolarAssessments = pgTable('energy_solar_assessments', {
  id: uuid('id').defaultRandom().primaryKey(),
  customerAccountId: uuid('customer_account_id').notNull().references(() => energyCustomerAccounts.id, { onDelete: 'cascade' }),
  buildingAssetId: uuid('building_asset_id').references(() => energyAssets.id, { onDelete: 'set null' }),
  assessedAt: timestamp('assessed_at', { withTimezone: true }).notNull().defaultNow(),
  annualConsumptionKwh: numeric('annual_consumption_kwh', { precision: 18, scale: 3 }).notNull(),
  daytimeSharePct: numeric('daytime_share_pct', { precision: 7, scale: 3 }),
  usableRoofAreaM2: numeric('usable_roof_area_m2', { precision: 14, scale: 3 }),
  irradiationKwhM2Year: numeric('irradiation_kwh_m2_year', { precision: 14, scale: 3 }),
  recommendedCapacityKwp: numeric('recommended_capacity_kwp', { precision: 14, scale: 3 }).notNull(),
  recommendedPanelCount: integer('recommended_panel_count'),
  recommendedInverterKw: numeric('recommended_inverter_kw', { precision: 14, scale: 3 }),
  recommendedBatteryKwh: numeric('recommended_battery_kwh', { precision: 14, scale: 3 }),
  gridAssetId: uuid('grid_asset_id').references(() => energyAssets.id, { onDelete: 'set null' }),
  feederAssetId: uuid('feeder_asset_id').references(() => energyAssets.id, { onDelete: 'set null' }),
  bayAssetId: uuid('bay_asset_id').references(() => energyAssets.id, { onDelete: 'set null' }),
  substationAssetId: uuid('substation_asset_id').references(() => energyAssets.id, { onDelete: 'set null' }),
  capacityAssessmentId: uuid('capacity_assessment_id').references(() => energyGridCapacityAssessments.id, { onDelete: 'set null' }),
  gridServiceLinkId: uuid('grid_service_link_id').references(() => energyCustomerGridServiceLinks.id, { onDelete: 'set null' }),
  gridMatchIsInferred: boolean('grid_match_is_inferred').notNull().default(false),
  gridAssessedAt: timestamp('grid_assessed_at', { withTimezone: true }),
  availableGridCapacityKw: numeric('available_grid_capacity_kw', { precision: 14, scale: 3 }),
  score: numeric('score', { precision: 7, scale: 3 }),
  factors: jsonb('factors').$type<Record<string, unknown>>().notNull().default({}),
  methodVersion: text('method_version').notNull(),
  inputHash: text('input_hash'),
  consumptionFrom: text('consumption_from'),
  consumptionTo: text('consumption_to'),
  roofSurfaceId: uuid('roof_surface_id').references(() => energyRoofSurfaces.id, { onDelete: 'set null' }),
  solarResourceZoneId: uuid('solar_resource_zone_id').references(() => energySolarResourceZones.id, { onDelete: 'set null' }),
  solarResourceRef: text('solar_resource_ref'),
  status: text('status').notNull().default('DRAFT'),
  confidence: numeric('confidence', { precision: 7, scale: 3 }),
  reviewedBy: text('reviewed_by'),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  reviewNote: text('review_note'),
  solarResourceVersion: text('solar_resource_version'),
}, (t) => [
  index('energy_solar_assessments_customer_time_idx').on(t.customerAccountId, t.assessedAt),
  index('energy_solar_assessments_status_idx').on(t.status, t.assessedAt),
  index('energy_solar_assessments_grid_link_idx').on(t.gridServiceLinkId),
  index('energy_solar_assessments_resource_idx').on(t.solarResourceZoneId),
]);

export const energySolarDesigns = pgTable('energy_solar_designs', {
  id: uuid('id').defaultRandom().primaryKey(),
  assessmentId: uuid('assessment_id').references(() => energySolarAssessments.id, { onDelete: 'set null' }),
  buildingAssetId: uuid('building_asset_id').references(() => energyAssets.id, { onDelete: 'set null' }),
  code: text('code').notNull(),
  name: text('name').notNull(),
  status: text('status').notNull().default('DRAFT'),
  currentVersion: integer('current_version').notNull().default(1),
  createdBy: text('created_by'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('energy_solar_designs_code_uq').on(t.code)]);

export const energySolarDesignVersions = pgTable('energy_solar_design_versions', {
  id: uuid('id').defaultRandom().primaryKey(),
  designId: uuid('design_id').notNull().references(() => energySolarDesigns.id, { onDelete: 'cascade' }),
  versionNo: integer('version_no').notNull(),
  status: text('status').notNull().default('DRAFT'),
  sceneState: jsonb('scene_state').$type<Record<string, unknown>>().notNull().default({}),
  engineeringState: jsonb('engineering_state').$type<Record<string, unknown>>().notNull().default({}),
  totalCapacityKwp: numeric('total_capacity_kwp', { precision: 14, scale: 3 }).notNull().default('0'),
  annualYieldKwh: numeric('annual_yield_kwh', { precision: 18, scale: 3 }),
  capex: numeric('capex', { precision: 20, scale: 2 }),
  paybackYears: numeric('payback_years', { precision: 10, scale: 2 }),
  avoidedCo2eKgYear: numeric('avoided_co2e_kg_year', { precision: 20, scale: 3 }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [uniqueIndex('energy_solar_versions_design_no_uq').on(t.designId, t.versionNo)]);

/**
 * Public, low-friction rooftop-solar screening requests. These are deliberately
 * separate from the technical customer/account assessment workflow so a citizen
 * can get an indicative result without an electricity account or GIS asset.
 */
export const energySolarConsultations = pgTable('energy_solar_consultations', {
  id: uuid('id').defaultRandom().primaryKey(),
  code: text('code').notNull(),
  customerName: text('customer_name'),
  district: text('district'),
  propertyType: text('property_type').notNull(),
  monthlyBillVnd: numeric('monthly_bill_vnd', { precision: 18, scale: 2 }).notNull(),
  roofSize: text('roof_size').notNull(),
  roofAreaM2: numeric('roof_area_m2', { precision: 12, scale: 2 }).notNull(),
  wantsBattery: boolean('wants_battery').notNull().default(false),
  batteryPriority: text('battery_priority'),
  result: jsonb('result').$type<Record<string, unknown>>().notNull().default({}),
  designState: jsonb('design_state').$type<Record<string, unknown>>().notNull().default({}),
  methodVersion: text('method_version').notNull().default('citizen-screening-v1'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  uniqueIndex('energy_solar_consultations_code_uq').on(t.code),
  index('energy_solar_consultations_created_idx').on(t.createdAt),
]);
