import { and, eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { energyEvConnectors, energyEvSessions } from '@/db/schema';
import { db } from '@/lib/db';

export const dynamic = 'force-dynamic';
type Context = { params: Promise<{ sessionId: string }> };
const patchSchema = z.object({ endedAt: z.string().nullable().optional(), energyKwh: z.number().finite().min(0).nullable().optional(), peakPowerKw: z.number().finite().min(0).nullable().optional(), status: z.enum(['ACTIVE', 'COMPLETED', 'CANCELLED', 'FAILED']).optional() });
function invalidId(id: string) { return !z.string().uuid().safeParse(id).success; }

export async function GET(_request: Request, context: Context) { try { const { sessionId } = await context.params; if (invalidId(sessionId)) return NextResponse.json({ message: 'Mã session không hợp lệ.' }, { status: 400 }); const [item] = await db.select().from(energyEvSessions).where(eq(energyEvSessions.id, sessionId)).limit(1); if (!item) return NextResponse.json({ message: 'Không tìm thấy session.' }, { status: 404 }); return NextResponse.json({ ...item, energyKwh: item.energyKwh == null ? null : Number(item.energyKwh), peakPowerKw: item.peakPowerKw == null ? null : Number(item.peakPowerKw) }); } catch (error) { return NextResponse.json({ message: error instanceof Error ? error.message : 'Không thể tải session.' }, { status: 500 }); } }

export async function PATCH(request: Request, context: Context) { try { const { sessionId } = await context.params; if (invalidId(sessionId)) return NextResponse.json({ message: 'Mã session không hợp lệ.' }, { status: 400 }); const payload = patchSchema.parse(await request.json()); const [existing] = await db.select().from(energyEvSessions).where(eq(energyEvSessions.id, sessionId)).limit(1); if (!existing) return NextResponse.json({ message: 'Không tìm thấy session.' }, { status: 404 }); const endedAt = payload.endedAt === undefined ? existing.endedAt : payload.endedAt ? new Date(payload.endedAt) : null; if (endedAt && endedAt < existing.startedAt) return NextResponse.json({ message: 'endedAt phải sau startedAt.' }, { status: 400 }); const [updated] = await db.transaction(async (tx) => { const [row] = await tx.update(energyEvSessions).set({ endedAt, energyKwh: payload.energyKwh === undefined ? existing.energyKwh : payload.energyKwh == null ? null : String(payload.energyKwh), peakPowerKw: payload.peakPowerKw === undefined ? existing.peakPowerKw : payload.peakPowerKw == null ? null : String(payload.peakPowerKw), status: payload.status ?? existing.status }).where(eq(energyEvSessions.id, sessionId)).returning(); if (payload.status) await tx.update(energyEvConnectors).set({ status: payload.status === 'ACTIVE' ? 'OCCUPIED' : payload.status === 'FAILED' ? 'FAULTED' : 'AVAILABLE' }).where(eq(energyEvConnectors.id, existing.connectorId)); return [row] as const; }); return NextResponse.json(updated); } catch (error) { if (error instanceof z.ZodError) return NextResponse.json({ message: 'Session không hợp lệ.', issues: error.issues }, { status: 400 }); return NextResponse.json({ message: error instanceof Error ? error.message : 'Không thể cập nhật session.' }, { status: 400 }); } }

export async function DELETE(_request: Request, context: Context) { try { const { sessionId } = await context.params; if (invalidId(sessionId)) return NextResponse.json({ message: 'Mã session không hợp lệ.' }, { status: 400 }); const [existing] = await db.select().from(energyEvSessions).where(eq(energyEvSessions.id, sessionId)).limit(1); if (!existing) return NextResponse.json({ message: 'Không tìm thấy session.' }, { status: 404 }); const [updated] = await db.update(energyEvSessions).set({ status: 'CANCELLED', endedAt: existing.endedAt ?? new Date() }).where(and(eq(energyEvSessions.id, sessionId), eq(energyEvSessions.status, 'ACTIVE'))).returning(); if (!updated) return NextResponse.json({ message: 'Session đã kết thúc; không xoá dữ liệu vận hành.' }, { status: 409 }); return NextResponse.json(updated); } catch (error) { return NextResponse.json({ message: error instanceof Error ? error.message : 'Không thể archive session.' }, { status: 400 }); } }
