import { eq } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { energyEvStationSnapshots } from '@/db/schema';
import { db } from '@/lib/db';

export const dynamic = 'force-dynamic';
type Context = { params: Promise<{ snapshotId: string }> };
const patchSchema = z.object({ measuredAt: z.string().min(1).optional(), availableCount: z.number().int().min(0).optional(), occupiedCount: z.number().int().min(0).optional(), faultedCount: z.number().int().min(0).optional(), utilizationPct: z.number().finite().min(0).max(100).optional(), energyDeliveredKwh: z.number().finite().min(0).nullable().optional(), peakPowerKw: z.number().finite().min(0).nullable().optional(), source: z.string().trim().min(2).max(80).optional() });
function invalidId(id: string) { return !z.string().uuid().safeParse(id).success; }

export async function GET(_request: Request, context: Context) { try { const { snapshotId } = await context.params; if (invalidId(snapshotId)) return NextResponse.json({ message: 'Mã snapshot không hợp lệ.' }, { status: 400 }); const [item] = await db.select().from(energyEvStationSnapshots).where(eq(energyEvStationSnapshots.id, snapshotId)).limit(1); if (!item) return NextResponse.json({ message: 'Không tìm thấy snapshot.' }, { status: 404 }); return NextResponse.json({ ...item, utilizationPct: Number(item.utilizationPct), energyDeliveredKwh: item.energyDeliveredKwh == null ? null : Number(item.energyDeliveredKwh), peakPowerKw: item.peakPowerKw == null ? null : Number(item.peakPowerKw) }); } catch (error) { return NextResponse.json({ message: error instanceof Error ? error.message : 'Không thể tải snapshot.' }, { status: 500 }); } }

export async function PATCH(request: Request, context: Context) { try { const { snapshotId } = await context.params; if (invalidId(snapshotId)) return NextResponse.json({ message: 'Mã snapshot không hợp lệ.' }, { status: 400 }); const payload = patchSchema.parse(await request.json()); const [existing] = await db.select().from(energyEvStationSnapshots).where(eq(energyEvStationSnapshots.id, snapshotId)).limit(1); if (!existing) return NextResponse.json({ message: 'Không tìm thấy snapshot.' }, { status: 404 }); const available = payload.availableCount ?? existing.availableCount; const occupied = payload.occupiedCount ?? existing.occupiedCount; const faulted = payload.faultedCount ?? existing.faultedCount; const parsedDate = payload.measuredAt ? new Date(payload.measuredAt) : existing.measuredAt; if (Number.isNaN(parsedDate.getTime())) return NextResponse.json({ message: 'Thời điểm snapshot không hợp lệ.' }, { status: 400 }); const [updated] = await db.update(energyEvStationSnapshots).set({ measuredAt: parsedDate, availableCount: available, occupiedCount: occupied, faultedCount: faulted, utilizationPct: payload.utilizationPct === undefined ? existing.utilizationPct : String(payload.utilizationPct), energyDeliveredKwh: payload.energyDeliveredKwh === undefined ? existing.energyDeliveredKwh : payload.energyDeliveredKwh == null ? null : String(payload.energyDeliveredKwh), peakPowerKw: payload.peakPowerKw === undefined ? existing.peakPowerKw : payload.peakPowerKw == null ? null : String(payload.peakPowerKw), source: payload.source ?? existing.source }).where(eq(energyEvStationSnapshots.id, snapshotId)).returning(); return NextResponse.json(updated); } catch (error) { if (error instanceof z.ZodError) return NextResponse.json({ message: 'Snapshot không hợp lệ.', issues: error.issues }, { status: 400 }); return NextResponse.json({ message: error instanceof Error ? error.message : 'Không thể cập nhật snapshot.' }, { status: 400 }); } }

export async function DELETE(_request: Request, context: Context) { try { const { snapshotId } = await context.params; if (invalidId(snapshotId)) return NextResponse.json({ message: 'Mã snapshot không hợp lệ.' }, { status: 400 }); const [existing] = await db.select().from(energyEvStationSnapshots).where(eq(energyEvStationSnapshots.id, snapshotId)).limit(1); if (!existing) return NextResponse.json({ message: 'Không tìm thấy snapshot.' }, { status: 404 }); const [updated] = await db.update(energyEvStationSnapshots).set({ source: 'ARCHIVED', metadata: { ...(existing.metadata ?? {}), archived: true, archivedAt: new Date().toISOString() } }).where(eq(energyEvStationSnapshots.id, snapshotId)).returning(); return NextResponse.json(updated); } catch (error) { return NextResponse.json({ message: error instanceof Error ? error.message : 'Không thể archive snapshot.' }, { status: 400 }); } }
