import { sql } from 'drizzle-orm';
import { NextResponse } from 'next/server';
import { z } from 'zod';
import { db } from '@/lib/db';

export const dynamic = 'force-dynamic';
const dateOnly = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Ngày phải có dạng YYYY-MM-DD.').refine((value) => { const date = new Date(`${value}T00:00:00.000Z`); return !Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === value; }, 'Ngày lịch không hợp lệ.');
const querySchema = z.object({ from: dateOnly, to: dateOnly, statusMode: z.enum(['OFFICIAL', 'SUBMITTED', 'ALL']).default('OFFICIAL'), energyTypeCode: z.string().trim().max(80).optional(), scope: z.enum(['SCOPE_1', 'SCOPE_2', 'SCOPE_3']).optional(), sector: z.string().trim().max(150).optional() }).refine((value) => value.to >= value.from, { path: ['to'], message: 'Ngày kết thúc phải sau hoặc bằng ngày bắt đầu.' });
type Row = Record<string, unknown>;
type Feature = { type: 'Feature'; id: string; geometry: { type: string; coordinates: unknown }; properties: Record<string, unknown> };
type Collection = { type: 'FeatureCollection'; features: Feature[] };
function parseGeoJson(value: unknown) { if (typeof value !== 'string') return null; try { const parsed = JSON.parse(value) as { type?: unknown; coordinates?: unknown }; return typeof parsed.type === 'string' && parsed.coordinates !== undefined ? { type: parsed.type, coordinates: parsed.coordinates } : null; } catch { return null; } }
function statusFilter(mode: 'OFFICIAL' | 'SUBMITTED' | 'ALL') { return mode === 'OFFICIAL' ? sql`ea.status IN ('VERIFIED', 'APPROVED')` : mode === 'SUBMITTED' ? sql`ea.status IN ('SUBMITTED', 'VERIFIED', 'APPROVED')` : sql`ea.status IN ('DRAFT', 'SUBMITTED', 'VERIFIED', 'APPROVED')`; }
function periodFilter(from: string, to: string) { return sql`CASE WHEN ea.period ~ '^[0-9]{4}$' THEN to_date(ea.period || '-01', 'YYYY-MM') ELSE to_date(ea.period, 'YYYY-MM') END BETWEEN ${from}::date AND ${to}::date`; }
function collection(features: Array<Feature | null>): Collection { return { type: 'FeatureCollection', features: features.filter((item): item is Feature => Boolean(item)) }; }

export async function GET(request: Request) {
  try {
    const query = querySchema.parse(Object.fromEntries(new URL(request.url).searchParams)); const period = periodFilter(query.from, query.to); const statuses = statusFilter(query.statusMode);
    const [sourceRows, adminRows, projectRows, actionRows, missingGeometry, missingEnergyType] = await Promise.all([
      db.execute(sql`WITH activity_stats AS (SELECT ea.source_id, COALESCE(SUM(ea.co2e_kg),0)::double precision AS "co2eKg", COUNT(*)::int AS activities FROM energy_emission_activities ea WHERE ${period} AND ${statuses} GROUP BY ea.source_id) SELECT es.id, es.code, es.name, es.source_type AS "sourceType", es.energy_type_code AS "energyTypeCode", et.name AS "energyTypeName", es.scope, es.sector, es.status, es.party_id AS "partyId", es.site_id AS "siteId", site.name AS "siteName", site.admin_area_code AS "adminAreaCode", COALESCE(aa.name, site.admin_area_code) AS "adminAreaName", COALESCE(ast."co2eKg",0)::double precision AS "co2eKg", COALESCE(ast.activities,0)::int AS activities, ST_AsGeoJSON(COALESCE(site.location::geometry, site.boundary)) AS geometry FROM energy_emission_sources es LEFT JOIN energy_energy_types et ON et.code = es.energy_type_code LEFT JOIN energy_sites site ON site.id = es.site_id LEFT JOIN energy_admin_areas aa ON aa.code = site.admin_area_code LEFT JOIN activity_stats ast ON ast.source_id = es.id WHERE es.status <> 'INACTIVE' AND (${query.energyTypeCode ?? null}::text IS NULL OR es.energy_type_code = ${query.energyTypeCode ?? null}) AND (${query.scope ?? null}::text IS NULL OR es.scope = ${query.scope ?? null}) AND (${query.sector ?? null}::text IS NULL OR es.sector = ${query.sector ?? null}) ORDER BY COALESCE(ast."co2eKg",0) DESC, es.name`),
      db.execute(sql`SELECT aa.id, aa.code, aa.name, aa.level, ST_AsGeoJSON(aa.boundary) AS geometry FROM energy_admin_areas aa WHERE aa.boundary IS NOT NULL`),
      db.execute(sql`SELECT cp.id, cp.code, cp.name, cp.project_type AS "projectType", cp.methodology, cp.registry, cp.status, site.name AS "siteName", ST_AsGeoJSON(COALESCE(site.location::geometry, site.boundary)) AS geometry FROM energy_carbon_projects cp LEFT JOIN energy_sites site ON site.id = cp.site_id WHERE cp.status <> 'CANCELLED'`),
      db.execute(sql`SELECT ra.id, ra.code, ra.name, ra.action_type AS "actionType", ra.status, ra.expected_reduction_tco2e_year AS "expectedReductionTco2eYear", ra.actual_reduction_tco2e_year AS "actualReductionTco2eYear", site.name AS "siteName", ST_AsGeoJSON(COALESCE(site.location::geometry, site.boundary)) AS geometry FROM energy_reduction_actions ra LEFT JOIN energy_sites site ON site.id = ra.site_id WHERE ra.status <> 'CANCELLED'`),
      db.execute(sql`SELECT COUNT(*)::int AS count FROM energy_emission_sources es LEFT JOIN energy_sites site ON site.id = es.site_id WHERE es.status <> 'INACTIVE' AND COALESCE(site.location::geometry, site.boundary) IS NULL`),
      db.execute(sql`SELECT COUNT(*)::int AS count FROM energy_emission_sources es WHERE es.status <> 'INACTIVE' AND es.energy_type_code IS NULL`),
    ]);
    const sources = (sourceRows.rows as Row[]).map((row) => { const geometry = parseGeoJson(row.geometry); return geometry ? { type: 'Feature' as const, id: String(row.id), geometry, properties: { layer: 'carbon-source', sourceId: row.id, code: row.code, name: row.name, sourceType: row.sourceType, energyTypeCode: row.energyTypeCode, energyTypeName: row.energyTypeName, scope: row.scope, sector: row.sector, status: row.status, partyId: row.partyId, siteId: row.siteId, siteName: row.siteName, adminAreaCode: row.adminAreaCode, adminAreaName: row.adminAreaName, co2eKg: Number(row.co2eKg ?? 0), co2eTco2e: Number(row.co2eKg ?? 0) / 1000, activities: Number(row.activities ?? 0) } } : null; });
    const admins = (adminRows.rows as Row[]).map((row) => { const geometry = parseGeoJson(row.geometry); return geometry ? { type: 'Feature' as const, id: String(row.id), geometry, properties: { layer: 'carbon-admin-area', adminAreaId: row.id, code: row.code, name: row.name, level: row.level } } : null; });
    const projects = (projectRows.rows as Row[]).map((row) => { const geometry = parseGeoJson(row.geometry); return geometry ? { type: 'Feature' as const, id: String(row.id), geometry, properties: { layer: 'carbon-project', projectId: row.id, code: row.code, name: row.name, projectType: row.projectType, methodology: row.methodology, registry: row.registry, status: row.status, siteName: row.siteName } } : null; });
    const actions = (actionRows.rows as Row[]).map((row) => { const geometry = parseGeoJson(row.geometry); return geometry ? { type: 'Feature' as const, id: String(row.id), geometry, properties: { layer: 'reduction-action', actionId: row.id, code: row.code, name: row.name, actionType: row.actionType, status: row.status, expectedReductionTco2eYear: row.expectedReductionTco2eYear == null ? null : Number(row.expectedReductionTco2eYear), actualReductionTco2eYear: row.actualReductionTco2eYear == null ? null : Number(row.actualReductionTco2eYear), siteName: row.siteName } } : null; });
    const layers = { sources: collection(sources), adminAreas: collection(admins), projects: collection(projects), actions: collection(actions) }; const allFeatures = Object.values(layers).flatMap((layer) => layer.features); const warnings: string[] = [];
    if (!allFeatures.length) warnings.push('CARBON_GIS_EMPTY: chưa có geometry thật trong Site, admin area, project hoặc action; hệ thống không tự geocode/tạo điểm thay thế.');
    if (Number((missingGeometry.rows[0] as Row | undefined)?.count ?? 0) > 0) warnings.push(`SOURCE_GEOMETRY_MISSING: ${Number((missingGeometry.rows[0] as Row | undefined)?.count ?? 0)} nguồn ACTIVE thiếu geometry Site.`);
    if (Number((missingEnergyType.rows[0] as Row | undefined)?.count ?? 0) > 0) warnings.push(`ENERGY_TYPE_MISSING: ${Number((missingEnergyType.rows[0] as Row | undefined)?.count ?? 0)} nguồn ACTIVE chưa phân loại canonical.`);
    return NextResponse.json({ period: { from: query.from, to: query.to, statusMode: query.statusMode }, layers, features: { type: 'FeatureCollection', features: allFeatures }, stats: { sources: layers.sources.features.length, adminAreas: layers.adminAreas.features.length, projects: layers.projects.features.length, actions: layers.actions.features.length, layerCounts: { sources: layers.sources.features.length, adminAreas: layers.adminAreas.features.length, projects: layers.projects.features.length, actions: layers.actions.features.length } }, warnings, method: { geometry: 'ST_AsGeoJSON(COALESCE(site.location::geometry, site.boundary)) + ST_AsGeoJSON(admin_area.boundary)', source: 'hệ thống GIS; no synthetic coordinate', activityFilter: query.statusMode === 'OFFICIAL' ? ['VERIFIED', 'APPROVED'] : query.statusMode === 'SUBMITTED' ? ['SUBMITTED', 'VERIFIED', 'APPROVED'] : ['DRAFT', 'SUBMITTED', 'VERIFIED', 'APPROVED'] } });
  } catch (error) { if (error instanceof z.ZodError) return NextResponse.json({ message: 'Bộ lọc Carbon GIS không hợp lệ.', issues: error.issues }, { status: 400 }); return NextResponse.json({ message: error instanceof Error ? error.message : 'Không thể tải Carbon GIS.' }, { status: 500 }); }
}
