import type { MissionKey } from './missions';

export type MissionAction = { title: string; description: string; href: string; badge?: string };

export const MISSION_ACTIONS: Record<MissionKey, MissionAction[]> = {
  grid: [
    { title: 'Danh mục nguồn dữ liệu', description: 'Quản lý đơn vị cung cấp, đơn vị phụ trách, tần suất cập nhật, mức độ tin cậy, phân loại và phiên bản của các nguồn dữ liệu dùng chung toàn nền tảng.', href: '/mission/grid/data-sources', badge: 'QUẢN TRỊ DỮ LIỆU' },
    { title: 'Danh mục hạ tầng lưới', description: 'Quản lý TBA, MBA, phát tuyến, đường dây, trụ/vị trí, ngày vận hành, thông số và tải hiện tại.', href: '/mission/grid/inventory', badge: 'HẠ TẦNG LƯỚI' },
    { title: 'Tải & cảnh báo quá tải', description: 'Theo dõi phụ tải hiện tại, phần công suất còn khả dụng, hệ số tải và lịch sử các lần chụp số liệu của TBA, phát tuyến và đường dây.', href: '/mission/grid/operations', badge: 'VẬN HÀNH' },
    { title: 'AI dự báo quá tải MBA', description: 'Dự báo phụ tải trong 24–168 giờ, khoảng tin cậy, thời điểm vượt định mức, cảnh báo rủi ro và lịch sử từng lần chạy AI.', href: '/mission/grid/ai-overload', badge: 'AI DỰ BÁO' },
    { title: 'Thống kê theo khu vực', description: 'Thống kê số lượng đường dây, trụ, TBA, MBA và công suất, phụ tải, khả năng còn lại theo địa giới hành chính.', href: '/mission/grid/analytics', badge: 'THỐNG KÊ KHU VỰC' },
    { title: 'Địa giới hành chính', description: 'Nhập ranh giới dạng đa giác GeoJSON của xã/phường/huyện để PostGIS tự phân vùng và tổng hợp hạ tầng lưới.', href: '/mission/grid/admin-areas', badge: 'ĐỊA GIỚI' },
    { title: 'Trạm biến áp', description: 'Danh mục trạm biến áp, công suất, phụ tải, tình trạng và vị trí trên bản đồ GIS.', href: '/mission/grid/substations', badge: 'TÀI SẢN' },
    { title: 'Trung tâm nhập dữ liệu EVN', description: 'Nạp tệp Excel, lưu dữ liệu chờ xử lý, kiểm tra hợp lệ, chuẩn hóa tài sản và dữ liệu đo.', href: '/mission/grid/imports', badge: 'LUỒNG NHẬP DỮ LIỆU' },
    { title: 'Kiểm soát chất lượng dữ liệu', description: 'Rà soát tọa độ, ngày vận hành, dữ liệu đo và ánh xạ bất thường theo từng bản ghi nguồn.', href: '/mission/grid/data-quality', badge: 'QUẢN TRỊ DỮ LIỆU' },
    { title: 'Giám sát thông số EVN', description: 'Theo dõi Ia/Ib/Ic, P, Q, cosφ tại từng điểm đo và lịch sử vận hành.', href: '/mission/grid/telemetry', badge: 'DỮ LIỆU ĐO' },
    { title: 'Cấu trúc liên kết lưới điện', description: 'Truy vết cấu trúc lưới điện theo chuỗi: TBA → MBA → ngăn lộ → xuất tuyến → tuyến → trạm hạ nguồn.', href: '/mission/grid/topology', badge: 'MÔ HÌNH LƯỚI' },
    { title: 'Bản đồ năng lượng', description: 'Bản đồ chuyên đề về lưới điện và dữ liệu năng lượng trên toàn tỉnh.', href: '/gis', badge: 'BẢN ĐỒ GIS' },
  ],
  generation: [
    { title: 'Điều hành nguồn điện', description: 'Tổng hợp công suất nguồn tái tạo theo loại hình, thông tin vận hành mới nhất, cảnh báo dự trữ và trạng thái quy hoạch.', href: '/mission/generation/analytics', badge: 'CHỈ SỐ ĐIỀU HÀNH' },
    { title: 'AI dự báo điện mặt trời', description: 'Dự báo công suất và sản lượng điện mặt trời trong 24–168 giờ, khoảng tin cậy, hệ số công suất và lịch sử từng lần chạy AI.', href: '/mission/generation/ai-solar', badge: 'AI DỰ BÁO' },
    { title: 'Dự án nguồn', description: 'Hồ sơ toàn diện về chủ đầu tư, tổ máy, thông số kỹ thuật, vận hành, đấu nối, quy hoạch và tài liệu liên quan.', href: '/mission/generation/projects', badge: 'HỒ SƠ DỰ ÁN' },
    { title: 'Nhiên liệu đầu vào', description: 'Theo dõi kho, lượng tồn có thể sử dụng, nhập/xuất, tốc độ tiêu thụ, số ngày duy trì, công suất tối đa có thể duy trì và nguồn xác nhận.', href: '/mission/generation/fuel', badge: 'NHIÊN LIỆU' },
    { title: 'Trữ lượng & khả năng duy trì', description: 'Quản lý nguồn sinh khối, LNG, rác, hồ chứa thủy điện và các dạng dự trữ khác; theo dõi số ngày duy trì, sản lượng quy đổi MWh và công suất tối đa MW.', href: '/mission/generation/reserves', badge: 'DỰ TRỮ' },
    { title: 'Quy hoạch & biên bản', description: 'Danh sách dự án trong kế hoạch năng lượng quốc gia/tỉnh, công suất quy hoạch, biên bản họp, quyết định và hồ sơ căn cứ.', href: '/mission/generation/planning', badge: 'QUY HOẠCH' },
  ],
  'rooftop-solar': [
    { title: 'Khách hàng điện mặt trời / EVN', description: 'Danh mục khách hàng, mã EVN, địa chỉ cấp điện và lịch sử tiêu thụ theo tháng.', href: '/mission/rooftop-solar/customers', badge: 'HỒ SƠ KHÁCH HÀNG' },
    { title: 'Hệ thống điện mặt trời đã lắp', description: 'Danh mục hệ thống điện mặt trời mái nhà đã lắp: công suất hiện hữu, bộ biến tần, pin lưu trữ, đấu nối, sản lượng và nguồn dữ liệu.', href: '/mission/rooftop-solar/systems', badge: 'ĐÃ LẮP ĐẶT' },
    { title: 'Phân tích theo địa bàn', description: 'Tách riêng công suất đã lắp với công suất tiềm năng và công suất đề xuất theo xã/phường/huyện.', href: '/mission/rooftop-solar/analytics', badge: 'CHỈ SỐ QUY HOẠCH' },
    { title: 'Bản đồ tư vấn điện mặt trời', description: 'Kết hợp thông tin khách hàng, ranh giới mái nhà, phiên bản dữ liệu bức xạ, phát tuyến/TBA, phần công suất còn khả dụng và các mái nhà lân cận trên PostGIS.', href: '/mission/rooftop-solar/gis', badge: 'TƯ VẤN BẢN ĐỒ' },
    { title: 'Tư vấn khách hàng điện mặt trời', description: 'Tra cứu thông tin EVN, tiêu thụ điện, mái nhà và lưới PostGIS; lưu lại kết quả đánh giá.', href: '/mission/rooftop-solar/advisor', badge: 'TƯ VẤN' },
    { title: 'AI gợi ý công suất điện mặt trời mái nhà', description: 'AI tạo các kịch bản điện mặt trời mái nhà từ kết quả đánh giá, tuân thủ giới hạn kỹ thuật và chuyển thẳng sang thiết kế 3D.', href: '/mission/rooftop-solar/ai-recommendation', badge: 'AI TƯ VẤN' },
    { title: 'Mô hình số điện mặt trời 3D', description: 'Thiết kế 3D, mô phỏng nắng và bóng đổ, bố trí tấm pin, khối lượng vật tư và hiệu quả dự kiến.', href: '/mission/rooftop-solar/designer', badge: 'THIẾT KẾ 3D' },
  ],
  efficiency: [
    { title: 'AI đọc & đối soát báo cáo EVN', description: 'Tải lên PDF/Excel/Word; AI trích xuất dữ liệu báo cáo, sau đó hệ thống đối chiếu theo quy tắc với dữ liệu EVN và hỗ trợ cán bộ rà soát.', href: '/mission/efficiency/reconciliation', badge: 'AI + ĐỐI SOÁT' },
    { title: 'Đơn vị sử dụng năng lượng trọng điểm', description: 'Quản lý hồ sơ đơn vị sử dụng năng lượng, công tơ và biểu đồ phụ tải.', href: '/mission/efficiency/consumers', badge: 'HỒ SƠ ĐƠN VỊ' },
    { title: 'Công tơ thông minh & dữ liệu theo thời gian', description: 'Quản lý công tơ, sự kiện, chỉ số chuẩn và dữ liệu tổng hợp theo giờ/ngày/tháng/năm từ hệ thống đo dùng chung.', href: '/mission/efficiency/meters', badge: 'CÔNG TƠ' },
    { title: 'Đường cơ sở & giải pháp tiết kiệm', description: 'Xác định đường cơ sở từ dữ liệu tiêu thụ EVN, quản lý mẫu số hoạt động, mức chuẩn có phiên bản và các biện pháp tiết kiệm.', href: '/mission/efficiency/baselines', badge: 'HIỆU QUẢ NĂNG LƯỢNG' },
    { title: 'Bản đồ hiệu quả & phân tích lưới', description: 'Bản đồ các đơn vị tiêu thụ trọng điểm, mức tăng trưởng, cường độ sử dụng, bất thường và tổng hợp theo phát tuyến/TBA/MBA.', href: '/mission/efficiency/gis', badge: 'CHỈ SỐ BẢN ĐỒ' },
  ],
  'grid-safety': [
    { title: 'Bảng điều hành an toàn', description: 'Chỉ số về hành lang, vi phạm, lịch cắt điện có kế hoạch, sự cố bất thường và tỷ lệ kết quả AI cần cán bộ rà soát theo kỳ dữ liệu thực.', href: '/mission/grid-safety/analytics', badge: 'CHỈ SỐ ĐIỀU HÀNH' },
    { title: 'Bản đồ an toàn & vùng ảnh hưởng', description: 'Hiển thị chồng lớp đường dây, hành lang, vi phạm, lần kiểm tra, kết quả AI, lịch cắt điện, công trình và địa giới từ PostGIS.', href: '/mission/grid-safety/gis', badge: 'BẢN ĐỒ POSTGIS' },
    { title: 'Danh mục văn bản & quy định', description: 'Quản lý văn bản pháp lý, các phiên bản quy định về khoảng cách an toàn và nguồn gốc dữ liệu hành lang trên PostGIS.', href: '/mission/grid-safety/regulations', badge: 'QUY ĐỊNH PHÁP LÝ' },
    { title: 'Kiểm tra khoảng cách công trình trên bản đồ', description: 'Quản lý hồ sơ xây dựng, vẽ/tải lên ranh giới công trình, chồng lớp với đường dây và hành lang, đồng thời lưu nhiều lần kiểm tra trên PostGIS.', href: '/mission/grid-safety/construction-gis', badge: 'KIỂM TRA BẢN ĐỒ' },
    { title: 'Phân tích ảnh hưởng mất điện EVN', description: 'Nhập dữ liệu thô từ EVN, xác định phát tuyến/đường dây/TBA, truy vết cấu trúc lưới và tổng hợp khách hàng, khu vực, MW cùng vùng ảnh hưởng.', href: '/mission/grid-safety/outages', badge: 'ẢNH HƯỞNG MẤT ĐIỆN' },
    { title: 'Quy trình kiểm tra & xử lý vi phạm', description: 'Quản lý ảnh hiện trường, kết quả AI, rà soát của cán bộ, phân công/thời hạn xử lý, bằng chứng khắc phục và xác minh/đóng hồ sơ.', href: '/mission/grid-safety/inspections', badge: 'QUY TRÌNH HIỆN TRƯỜNG' },
    { title: 'AI kiểm tra an toàn bằng hình ảnh', description: 'Phân tích ảnh, đối chiếu vị trí thiết bị và để cán bộ kiểm tra kết quả trước khi lập hồ sơ vi phạm.', href: '/mission/grid-safety/ai-vision', badge: 'AI + DUYỆT' },
    { title: 'Kiểm tra cấp phép xây dựng', description: 'Dùng PostGIS kiểm tra vị trí công trình với đường dây và quy định hành lang đang có hiệu lực.', href: '/mission/grid-safety/construction-check', badge: 'KIỂM TRA GIS' },
    { title: 'Hành lang & sự cố', description: 'Quản lý quy định, hành lang, vi phạm, lịch cắt điện, sự cố và bằng chứng hiện trường/AI.', href: '/mission/grid-safety/corridors', badge: 'AN TOÀN LƯỚI' },
  ],
  carbon: [
    { title: 'Danh mục loại năng lượng', description: 'Quản lý loại năng lượng chuẩn, nhóm năng lượng và đơn vị tính dùng chung cho danh mục nguồn, văn bản điều hành và chỉ số carbon.', href: '/mission/carbon/energy-types', badge: 'DANH MỤC CHUẨN' },
    { title: 'Dữ liệu thô VBĐH & liên kết', description: 'Tiếp nhận dữ liệu thô kèm mã nguồn, tài liệu và mã kiểm tra; kiểm soát việc liên kết sang hoạt động phát thải hoặc số đo; hiển thị trung thực trạng thái xử lý.', href: '/mission/carbon/vbdh', badge: 'NGUỒN GỐC DỮ LIỆU' },
    { title: 'Danh mục giảm phát thải', description: 'Quản lý đường cơ sở, mục tiêu theo năm, hoạt động, tiến độ, bằng chứng và trạng thái xác minh cho chương trình giảm phát thải.', href: '/mission/carbon/reduction', badge: 'GIẢM PHÁT THẢI' },
    { title: 'Sổ theo dõi tín chỉ carbon', description: 'Quản lý dự án, lô tín chỉ và giao dịch theo lịch sử nối tiếp; kiểm soát số dư trước khi giữ chỗ, chuyển nhượng, hủy sử dụng hoặc hủy giao dịch.', href: '/mission/carbon/credits', badge: 'SỔ TÍN CHỈ' },
    { title: 'Phân tích carbon', description: 'Chỉ số phát thải, phân tích theo loại năng lượng/phạm vi/lĩnh vực và nguồn gốc của số liệu thực.', href: '/mission/carbon/analytics', badge: 'CHỈ SỐ' },
    { title: 'Bản đồ carbon', description: 'Bản đồ nguồn phát thải, dự án và hoạt động giảm phát thải từ hình học PostGIS, kèm cảnh báo dữ liệu thiếu.', href: '/mission/carbon/gis', badge: 'BẢN ĐỒ POSTGIS' },
    { title: 'Nguồn phát thải', description: 'Quản lý đơn vị, địa điểm/khu vực, loại nguồn, phạm vi phát thải và lĩnh vực để phục vụ bản đồ carbon.', href: '/mission/carbon/sources', badge: 'DANH MỤC NGUỒN' },
    { title: 'Kiểm kê phát thải', description: 'Theo dõi CO₂e, NOx/SOx, hệ số có phiên bản, kế hoạch giảm phát thải, tín chỉ carbon và thống kê theo khu vực/lĩnh vực.', href: '/mission/carbon/inventory', badge: 'KHÍ NHÀ KÍNH' },
    { title: 'AI phân tích báo cáo carbon', description: 'Tải lên PDF/XLSX/DOCX; AI trích xuất phạm vi phát thải 1/2/3 và nguồn gốc dữ liệu, so sánh với danh mục carbon, phiên bản hệ số phát thải và hỗ trợ cán bộ rà soát.', href: '/mission/carbon/ai-report', badge: 'AI + KHÍ NHÀ KÍNH' },
    { title: 'Nghĩa vụ báo cáo', description: 'Theo dõi hạn nộp, hồ sơ từ VBĐH và quy trình rà soát/chấp thuận.', href: '/mission/carbon/obligations', badge: 'VBĐH' },
  ],
  'ev-charging': [
    { title: 'Danh mục khách hàng EV', description: 'Danh mục khách hàng duy nhất, mã khách hàng không trùng, nhiều hồ sơ đăng ký và thông tin khách hàng 360°.', href: '/mission/ev-charging/customers', badge: 'HỒ SƠ KHÁCH HÀNG' },
    { title: 'Hồ sơ đăng ký trạm sạc', description: 'Quản lý khách hàng, khu vực, công suất yêu cầu, tự động xác định kết nối lưới, thẩm định và chuyển thành trạm.', href: '/mission/ev-charging/applications', badge: 'QUY TRÌNH HỒ SƠ' },
    { title: 'Trạm sạc & vận hành', description: 'Quản lý trạm sạc, đầu sạc, tình trạng sẵn sàng/mức sử dụng theo từng lần chụp và các phiên sạc.', href: '/mission/ev-charging/stations', badge: 'HỒ SƠ TRẠM SẠC' },
    { title: 'Phân tích trạm sạc EV', description: 'Tổng hợp khách hàng duy nhất, công suất đăng ký/được duyệt/đấu nối/đã lắp, phễu xử lý và phần công suất còn khả dụng theo từng tài sản lưới.', href: '/mission/ev-charging/analytics', badge: 'CHỈ SỐ ĐIỀU HÀNH' },
    { title: 'Bản đồ trạm sạc EV', description: 'Hiển thị hồ sơ đăng ký, trạm sạc, TBA/phát tuyến và địa giới từ hình học PostGIS thực; phân biệt đề xuất/đã duyệt/đang vận hành.', href: '/mission/ev-charging/gis', badge: 'BẢN ĐỒ POSTGIS' },
    { title: 'AI dự báo nhu cầu sạc EV', description: 'Dự báo số phiên sạc và công suất trong 24–168 giờ, phân bố công suất đăng ký và xếp hạng khu vực ưu tiên phát triển trạm sạc.', href: '/mission/ev-charging/ai-demand', badge: 'AI DỰ BÁO' },
  ],
};
